# This is a basic workflow to help you get started with Actions

name: Build and deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
 # pull_request:
 #   branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm run build
      
     # - name: Build and Deploy
     #   uses: grasilife/github-pages-deploy-action@master
    #    env:
   #       ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  #        BASE_BRANCH: master # The branch the action should deploy from.
 #         BRANCH: gh-pages # The branch the action should deploy to.
 #         FOLDER: build # The folder the action should deploy.
#          BUILD_SCRIPT: npm install && npm run-script build # The build script the action should run prior to deploying.:  
