name: Deploy to GH pages
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm ci
      - run: |
            git config user.name "techuser" && git config user.email "test@user.org"
            npm run gh-pages-deploy
